"""auto-vote

Revision ID: fcab9b67fb00
Revises: efbcd5a7dbbe
Create Date: 2025-11-11 20:58:25.594839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcab9b67fb00'
down_revision: Union[str, Sequence[str], None] = 'efbcd5a7dbbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    op.add_column('posts', sa.Column('text', sa.String(), nullable=False))
    op.add_column('posts', sa.Column('account_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('posts_users_fk'), 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'users', ['account_id'], ['id'], ondelete='CASCADE')
    op.drop_column('posts', 'account')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('account', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key(op.f('posts_users_fk'), 'posts', 'users', ['account'], ['id'], ondelete='CASCADE')
    op.drop_column('posts', 'account_id')
    op.drop_column('posts', 'text')
    op.drop_table('votes')
    # ### end Alembic commands ###
